### ISSUE TITLE
logout的问题

### ISSUE THREAD

**Issue by robbinhan** [tyua07/laravel-admin#1]
我run了你的代码，感觉很棒，但是在logout时遇到个问题，ajax需要返回json数据，但是实际返回是个html页面。
我看了代码发现，你封装了response方法，其中使用了die函数，我修改代码为直接echo后正常执行

**Comment by tyua07** [comment]
die 只是不执行后面的代码了，相比echo 都是输出！不可以这么去理解，不过最好 我还是建议封装一下 响应那块，用response()->json();这样去响应

**Comment by tyua07** [comment]
“不可以这么去理解” 打错字了 应该是“可以这么去理解”
