### ISSUE TITLE
上传文件是提示错误，但实际已存储到七牛空间中

### ISSUE THREAD

**Issue by abcsun** [tyua07/laravel-admin#3]
hi，跑了下你的后台，感觉不错，对于二次开发很方便。
在测试upload的时候，文件submit后已经在七牛中看到，但是前端还是红色错误提示，看到你在处理文件时候添加了persistentFop，我注释掉相关持久化处理代码后文件倒是能正常上传了，前端也是正确的标志，不知道是我关于持久化配置有问题还是这部分功能暂未实现？多谢。

**Comment by tyua07** [comment]
应该是你没有安装swoole扩展的问题导致的，关于上传文件，个人觉得不是很完美，我用了swoole扩展的task实现了 异步任务，如果没有这方面的需求，你可以把持久化任务给去掉，等我有空写好了，再回复你，还有你也可以扩展我的异步任务！谢谢
