### ISSUE TITLE
谢谢楼主！很吸引人，但是不知道该怎么部署，laravel新手

### ISSUE THREAD

**Issue by NixusCN** [tyua07/laravel-admin#4]
可以出一个installations吗？
谢谢

**Comment by tyua07** [comment]
可以，晚点 我再出，我现在写代码中！理解哈

**Comment by NixusCN** [comment]
非常理解，谢谢，非常感谢！

**Comment by NixusCN** [comment]
我可以多问一句吧，不知道会不会冒犯您：为什么你可以这么牛？我连这个框架怎么用都没学会(:

**Comment by tyua07** [comment]
哥，我不牛啊，这个东西我还有很多没有完善，最近没有空写，在我梳理好后，会更新很多东西的

**Comment by tyua07** [comment]
我开始写文档了，请看 [文档手册](http://laravel-admin.mydoc.io/?t=32958 ),这个还没有更新，需要时间，但是可以先给你预览一下
