### ISSUE TITLE
说明中对于配置默认使用redis方面只字不提？

### ISSUE THREAD

**Issue by peinhu** [tyua07/laravel-admin#5]
运行直接报错，谷歌了才知道原因。。
migrations文件夹里面什么都没有，数据库呢？找了半天，原来要另外下载。。。

**Comment by tyua07** [comment]
我默认session就是redis，我想这种问题不需要说明吧，还有数据库，我readme写的很清楚，而且以前的issue我也有回答！

**Comment by tyua07** [comment]
关于文档，我这里详细说明一下，[http://laravel-admin.mydoc.io/?t=32958](http://laravel-admin.mydoc.io/?t=32958)这个地址是我现在再更新的文档，但是源码 我最近都是没有提交，因为我现在是在正式环境上面用，等到了稳定之后，我会发布出来的，如果你愿意留下你的邮箱，到时候 我会发邮件给你，谢谢！

**Comment by tyua07** [comment]
还有说句题外话，现在我再准备辞职的事情，所以更新代码会慢，可能到了一个点，我才会整理代码，所以 希望理解

**Comment by leoxml** [comment]
ConnectionException in AbstractConnection.php line 155: ����Ŀ����������ܾ����޷����ӡ� [tcp://127.0.0.1:6379]

浏览器运行出现如上错误，蒙了，求解？

**Comment by tyua07** [comment]
这个是redis的默认端口，是不是你的机器没有redis环境，你可以把你的redis 换成file

**Comment by leoxml** [comment]
恩，我是在windows上，改成file后，前台登录页显示，不过缺少user_profile表：SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.user_profile' doesn't exist (SQL: select * from `user_profile` where `user_info_id` = 8 limit 1)

**Comment by tyua07** [comment]
我把sql重新更新一下

**Comment by tyua07** [comment]
数据库模型我重新上传了，但是sql没有更新，你可以把数据库模型导成sql，然后自己加一条记录
